name: 18 rue Divona
description: Carnet de notes
meta_description: "Carnet de notes et tableaux de bord abordant la quantification personnels (quantified self)"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://18ruedivona.eu'
author:         'Cyril Gravelier'
