# Theme settings
logo: false
name:             "18 rue Divona"
description:      "Carnet de notes"
meta_description: "Carnet de notes et tableaux de bord abordant la quantification personnels (quantified self)"

# Details for the RSS feed generator
url:            'http://18ruedivona.eu'
author:         'Cyril Gravelier'

# Conversion
markdown:           redcarpet
highlighter:        pygments
excerpt_separator:  "<!--more-->"
paginate:           15

# Outputting
permalink: /blog/:year/:month/:title

# Your disqus shortname, entering this will enable commenting on posts
disqus: 'divona'

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 'UA-27130228-2'

# Prose.io configuration
prose:
  rooturl:        ''
  siteurl:        'http://18ruedivona.eu/'
  relativeLinks:  'http://18ruedivona.eu/links.jsonp'
  media:          'media'
  ignore:
    - .gitignore
    - _config.yml
    - CNAME
    - feed.xml
    - index.html
    - LICENSE.txt
    - links.jsonp
    - README.md
    - /_includes
    - /_layouts
    - /assets
  metadata:
    _posts:
      - name: "layout"
        field:
          element:  "hidden"
          value:    "post"
      - name: "date"
        field:
          element:  "text"
          label:    "Date"
          help:     "YYYY-MM-DD hh:mm:ss"
      - name: "categories"
        field:
          element:      "multiselect"
          label:        "Add categories"
          placeholder:  "Choose categories"
          alterable:    true
          options:
            - name:   "Sport"
              value:  "sport"
            - name:   "Quantified Self"
              value:  "quantified self"
